Created new branch
andela/healthchecks_akira pull request #22
Opened 2017-03-14 08:20 UTC by Gathondu

Added local settings.py

2017-03-14 12:29 UTC, osule requested changes

2017-03-14 12:29 UTC, andela-osule commented on hc/api/management/commands/sendalerts.py
> +        going_down = query.filter(alert_after__lt=now, status = "up")
Catch this space

2017-03-14 12:29 UTC, andela-osule commented on hc/api/models.py
> +            if self.status == "often":
This doesn't need to be nested. We really don't require to check this condition`self.last_ping + self.timeout + self.grace > now` to return a status for _often_ checks

2017-03-14 12:29 UTC, andela-osule commented on hc/api/views.py
> +        check.alert_often_pings = True
Why do we require _alert_often_pings_ together with status to know if a check alerts often?

2017-03-15 06:43 UTC, NgangaMaryanne commented
making reviews

2017-03-15 16:06 UTC, NgangaMaryanne commented on hc/api/views.py
> +        check.alert_often_pings = True
The alert_often_pings is what stops the function sendalerts from sending too many alerts when a check is in often mode. without it, the alerts come every second. We were setting it to 'False' after sending one alert.

2017-03-17 08:00 UTC, osule approved these changes
LGTM

2017-03-17 08:01 UTC, merged