Ch accounts tests #139551323
andela/healthchecks_akira pull request #4
Opened 2017-02-22 11:34 UTC by daisyndungu

Add tests in Accounts.

2017-02-22 12:22 UTC, andela-osule commented on hc/accounts/tests/test_login.py
> +        # count before
Can we have this comment inlined with the previous line?

2017-02-22 12:37 UTC, andela-osule commented on hc/accounts/tests/test_login.py
> +        assert "To log into healthchecks.io" in mail.outbox[0].body
We should take advantage of assertion methods available in the django TestCase class. https://docs.djangoproject.com/en/1.10/topics/testing/tools/#django.test.SimpleTestCase.assertContains

2017-02-22 12:44 UTC, andela-osule commented on hc/accounts/tests/test_profile.py
> +        assert "link" in mail.outbox[0].body
Please use assertContains method available in Django SimpleTestCase class.
It provides metadata about the test on failure.

I'm well aware of other testing frameworks promoting use of assert stmts such as py.test but I think that if we are using Unittest here we should take advantage of the good things that it provides us with.
https://docs.python.org/2/reference/simple_stmts.html#the-assert-statement

2017-02-22 12:46 UTC, andela-osule commented on hc/accounts/tests/test_profile.py
> +        assert "link" in mail.outbox[0].body
Oh, and there is the issue of running python with the -O flag in an optimized state which loses assert stmts.

2017-02-22 12:47 UTC, andela-osule commented on hc/accounts/tests/test_profile.py
> +        assert "Hello,\n\nalice@example.org invites you" in mail.outbox[0].body
Please see previous review comments

2017-02-22 13:03 UTC, osule requested changes
Please see all review comments and attend to them accordingly.

2017-02-22 13:03 UTC, andela-osule commented on hc/accounts/tests/test_profile.py
> +    def test_it_creates_and_revokes_api_key(self):
We should be testing out this https://github.com/andela/healthchecks_akira/blob/df137bfdad57cb53bcf31bdc92056cb4f316f921/hc/accounts/views.py#L150

2017-02-22 13:03 UTC, andela-osule commented on hc/accounts/tests/test_switch_team.py
> +        assert r.status_code == 200
Please make use of `assertEqual` instance method of the Django TestCase class

2017-02-22 13:03 UTC, andela-osule commented on hc/accounts/tests/test_switch_team.py
> +        assert r.status_code == 403
Please use the assertEqual instance method of the Django TestCase class

2017-02-22 13:03 UTC, andela-osule commented on hc/accounts/tests/test_switch_team.py
> +        assert r.status_code == 200
Please see previous review comment about this

2017-02-22 13:03 UTC, andela-osule commented on hc/settings.py
> +# ALLOWED_HOSTS = []
What are your reasons for commenting this out?

2017-02-22 13:03 UTC, andela-osule commented on hc/settings.py
> +EMAIL_HOST = "smtp.gmail.com"
We shouldn't check this in.

2017-02-22 13:10 UTC, daisyndungu commented on hc/settings.py
> +# ALLOWED_HOSTS = []
I did this in order to get an actual email in my mailbox

2017-02-22 13:13 UTC, daisyndungu commented on hc/settings.py
> +EMAIL_HOST = "smtp.gmail.com"
I did this in order to get an actual email in my mailbox. I was using my gmail account but I'll change this back to the default settings.

2017-02-23 11:34 UTC, osule requested changes

2017-02-23 11:34 UTC, andela-osule commented on hc/settings.py
> +DATABASES = {
We shouldn't revert back the changes to the settings file.

2017-02-23 11:34 UTC, andela-osule commented on hc/accounts/tests/test_profile.py
> +    def test_it_creates_and_revokes_api_key(self):
@Andela-Didacus @daisyndungu We aren't exercising the API in this test. Please see my previous comment on this.

2017-02-23 15:46 UTC, daisyndungu reviewed
Changes made sucessfuly

2017-02-23 15:57 UTC, osule approved these changes
LGTM 👍

2017-02-23 15:58 UTC, merged